### ISSUE TITLE
Could not register AWS AccessKeyId and SecretKey 

### ISSUE THREAD

**Issue by kamal2222ahmed** [trackit/trackit2-home#57] opened 2017-11-24 22:09 UTC
Following the instructions at https://trackit.io/installing-trackit-on-aws-ec2-step-by-step/
Except, 
1. i could only use Redhat Enterprise Linux Server release 7.4
2. i used $sudo usermod -a -G docker ec2-user 

The application comes up ok, and i am able to login as admin/admin
but could not register the aws keys. After i press the Submit button, it turns grey but never returns me to the main page of application.

docker status:

$ docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
70a6530c95ab trackit_loadbalancer "nginx -g 'daemon ..." About an hour ago Up About an hour 0.0.0.0:80->80/tcp, 443/tcp trackit_loadbalancer_1
be2450da969b msolution/trackit_api:latest "/usr/bin/supervisord" About an hour ago Up About an hour trackit_api_1
03c73556266e msolution/trackit_ui:latest "/bin/sh -c ./serv..." About an hour ago Up About an hour 80/tcp trackit_webui_1
2f5864ff5c36 mariadb:latest "docker-entrypoint..." About an hour ago Up About an hour 3306/tcp trackit_mysql_1
a60b1c336d72 redis "docker-entrypoint..." About an hour ago Up About an hour 6379/tcp trackit_redis_1
51143aae3f0a elasticsearch:2.3.5 "/docker-entrypoin..." About an hour ago Up About an hour 9200/tcp, 9300/tcp trackit_es1_1

logs:

$docker logs -f trackit_loadbalancer_1

10.109.227.75 - - [24/Nov/2017:20:49:44 +0000] "POST /api/aws/accounts HTTP/1.1" 401 28 "http://10.193.206.13/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" "-"

$ docker logs -f trackit_api_1

File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1601, in _do_rollback
self.connection._rollback_impl()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 670, in _rollback_impl
self._handle_dbapi_exception(e, None, None, None, None)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
exc_info
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 668, in _rollback_impl
self.engine.dialect.do_rollback(self.connection)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2526, in do_rollback
dbapi_connection.rollback()
OperationalError: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')

2017-11-24 21:52:44,200 DEBG 'worker' stderr output:
[2017-11-24 21:52:44,200: ERROR/MainProcess] Task app.tasks.fetchs3pricing[6b0cd3d0-dfaf-44e6-826b-5f43a25af0f9] raised unexpected: ConnectionError(MaxRetryError('None: Max retries exceeded with url: /offers/v1.0/aws/AmazonS3/current/index.json (Caused by None)',),)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
R = retval = fun(args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call_
return self.run(args, *kwargs)
File "/root/api/app/tasks.py", line 297, in fetch_s3pricing
s3pricing.fetch()
File "/root/api/app/s3pricing.py", line 25, in fetch
return aws_pricing.fetch('AmazonS3')
File "/root/api/app/aws/pricing.py", line 21, in fetch
res = requests.get(PRICING_URL_TPL % offer, headers=headers)
File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
return request('get', url, params=params, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
return session.request(method=method, url=url, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
resp = self.send(prep, *send_kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
r = adapter.send(request, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
raise ConnectionError(e, request=request)
ConnectionError: None: Max retries exceeded with url: /offers/v1.0/aws/AmazonS3/current/index.json (Caused by None)

$ docker logs -f trackit_redis_1

1:M 24 Nov 20:35:37.590 # Server initialized
1:M 24 Nov 20:35:37.590 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 24 Nov 20:35:37.590 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 24 Nov 20:35:37.590 * Ready to accept connections
1:M 24 Nov 21:05:46.165 * 100 changes in 300 seconds. Saving...
1:M 24 Nov 21:05:46.166 * Background saving started by pid 16
16:C 24 Nov 21:05:46.172 * DB saved on disk
16:C 24 Nov 21:05:46.172 * RDB: 6 MB of memory used by copy-on-write
1:M 24 Nov 21:05:46.266 * Background saving terminated with success
1:M 24 Nov 21:35:46.146 * 100 changes in 300 seconds. Saving...
1:M 24 Nov 21:35:46.146 * Background saving started by pid 17
17:C 24 Nov 21:35:46.149 * DB saved on disk
17:C 24 Nov 21:35:46.150 * RDB: 6 MB of memory used by copy-on-write
1:M 24 Nov 21:35:46.246 * Background saving terminated with success

Intermittently, i also get.
There was a problem with the API. Please try signing out and in again.

**Comment by thibautcornolti** [comment] 2017-11-28 02:16
Hi kamal2222ahmed,

Are you sure that the trackit_mysql_1 docker is working properly? Could you check the logs exactly like you did before? `docker logs -f trackit_mysql_1`
Which instance type have you taken in AWS EC2?
It seems to be from the SQL server.
We are going to test TrackIt with the method from https://trackit.io/installing-trackit-on-aws-ec2-step-by-step/ with Redhat Enterprise Linux Server release 7.4 and we will come back to you as soon as possible.

Thank you for this well documented issue.

**Comment by kamal2222ahmed** [comment] 2017-12-04 11:25
```
[ec2-user@ip-10-103-159-207 trackit]$ docker logs -f trackit_mysql_1
Initializing database

error from daemon in stream: Error grabbing logs: unexpected EOF
ec2 instance type is m3.xlarge
```
awaiting your results for RHEL 7.4, Thanks
also:
```
[ec2-user@ip-10-103-159-207 trackit]$ docker ps -l
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                         NAMES
ce106444784d        trackit_loadbalancer   "nginx -g 'daemon ofâ¦"   9 minutes ago       Up 9 minutes        0.0.0.0:80->80/tcp, 443/tcp   trackit_loadbalancer_1
[ec2-user@ip-10-103-159-207 trackit]$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                     PORTS                         NAMES
ce106444784d        trackit_loadbalancer           "nginx -g 'daemon ofâ¦"   9 minutes ago       Up 9 minutes               0.0.0.0:80->80/tcp, 443/tcp   trackit_loadbalancer_1
d5bb6e77435e        msolution/trackit_api:latest   "/usr/bin/supervisord"   9 minutes ago       Up 9 minutes                                             trackit_api_1
5e9b60f6e5e2        elasticsearch:2.3.5            "/docker-entrypoint.â¦"   9 minutes ago       Up 9 minutes               9200/tcp, 9300/tcp            trackit_es1_1
bc9bff672762        redis                          "docker-entrypoint.sâ¦"   9 minutes ago       Up 9 minutes               6379/tcp                      trackit_redis_1
69c2d9af7406        msolution/trackit_ui:latest    "/bin/sh -c ./serverâ¦"   9 minutes ago       Up 9 minutes               80/tcp                        trackit_webui_1
53b7c9504381        mariadb:latest                 "docker-entrypoint.sâ¦"   9 minutes ago       Exited (1) 9 minutes ago                                 trackit_mysql_1
```
indicates its marisdb that exited

**Comment by thibautcornolti** [comment] 2017-12-06 12:20
Hi kamal2222ahmed,

We reproduced the procedure and TrackIt works as expected with Red Hat Enterprise Linux 7.4.
You should try to follow again the installation on a new and clean instance.

If you have any questions, ask us!

Thanks.

**Comment by lfrancois** [comment] 2017-12-11 15:55
Hi @kamal2222ahmed ! Did you make any progress running trackit? Also would be happy to jump in a webex with you to try to get your system up and running and better understand the issue you are facing.

Best Regards,
Ludo

**Comment by zanchi-r** [comment] 2018-01-17 12:37
Closing this issue, this version of trackit is now on [trackit-legacy](https://github.com/trackit/trackit-legacy)

**Closed as completed by zanchi-r** 2018-01-17 12:37 UTC
